import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/components/lenis-provider";
// import Navbar from "@/components/navbar";
import { Toaster } from "sonner";
import TransitionsProvider from "@/components/transitionsProvider";

const inter = Inter_Tight({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {/* <Navbar /> */}

        <LenisProvider>
          <TransitionsProvider>
            <main>{children}</main>
            <Toaster />
          </TransitionsProvider>
        </LenisProvider>
      </body>
    </html>
  );
}
