import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar";
import { Toaster } from "sonner";
import TransitionsProvider from "@/components/transitionsProvider";
import { ThemeProvider } from "@/components/theme/theme-provider";

const inter = Inter_Tight({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        {/* <Navbar /> */}

        <TransitionsProvider>
          <main>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </main>
          <Toaster />
        </TransitionsProvider>
      </body>
    </html>
  );
}
